version: '3.8'

services:
  bookinsight.ui:
    container_name: blazor
    image: bookinsight.ui
    build:
      context: .
      dockerfile: BookInsight.UI/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  bookinsight.api:
    container_name: webapi
    image: bookinsight.api
    build:
      context: .
      dockerfile: BookInsight.API/Dockerfile 
    ports:
      - "5001:81"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:81